name: R Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  matrix_build:
    runs-on: ubuntu-latest  # Cambia a macos-latest si persisten los problemas
    strategy:
      matrix:
        r-version: ['4.1.1', '4.2.2']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base

      - name: Verify R Installation
        run: |
          Rscript --version || echo "R not found."

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Test Internet Connection
        run: |
          Rscript -e 'if (!curl::has_internet()) stop("No internet connection.")'

      - name: Install Dependencies
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org"))'
          Rscript -e 'install.packages(c("curl", "httr", "remotes", "rcmdcheck"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Enhanced Logging
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org"), verbose = TRUE)'

      - name: Check Project
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
