name: R Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  matrix_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.2', '4.1.1']  # Verifica estas versiones soportadas

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify R Installation
        run: |
          Rscript --version || echo "R is not installed."

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages(c("curl", "httr", "remotes", "rcmdcheck"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Enhanced Logging
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org"), verbose = TRUE)'

      - name: Check Project
        run: |
          Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
