name: R Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  matrix_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Aumentar tiempo permitido para evitar cancelaciones
    strategy:
      matrix:
        r-version: ['4.1.1', '4.2.2']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base

      - name: Verify R Installation
        run: |
          Rscript --version || echo "R installation failed."

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages(c("httr", "remotes", "rcmdcheck"), repos = "https://cloud.r-project.org")'

      - name: Check Project
        run: |
          Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
