name: R Package Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install System Libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Configure R Library Path
        run: |
          export R_LIBS_USER="/home/runner/work/_temp/Rlibs"
          mkdir -p $R_LIBS_USER

      - name: Install R
        run: |
          sudo apt-get install -y r-base

      - name: Verify R Installation
        run: |
          Rscript --version || echo "R installation failed."

      - name: Install curl Package
        run: |
          Rscript -e 'install.packages("curl", lib="/home/runner/work/_temp/Rlibs", dependencies = TRUE, repos = "https://cloud.r-project.org")'
      
      # Verificar que el paquete curl se haya instalado correctamente
      - name: Verify curl Installation
        run: |
          Rscript -e 'if ("curl" %in% rownames(installed.packages())) {cat("curl is installed successfully.")} else {cat("curl installation failed.")}'

      - name: Verify R Library Path
        run: |
          Rscript -e '.libPaths()'

      - name: Check Package
        run: |
          Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
