name: R Workflow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  matrix_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.1', '4.2.2']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "rcmdcheck"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
          Rscript -e 'install.packages(c("curl", "httr"))'

      - name: Check Project
        run: |
          Rscript -e 'if (!curl::has_internet()) stop("No internet connection.")'
          Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
