name: R Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Cambiar a "write" si el workflow debe modificar el repositorio

jobs:
  matrix_build:
    runs-on: ubuntu-latest  # Cambiado a Ubuntu para mayor compatibilidad
    strategy:
      matrix:
        r-version: ['4.1.1', '4.2.2']  # Eliminamos la versi√≥n 3.6.3 y usamos versiones soportadas

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar R
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "rcmdcheck"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      # 4. Verificar proyecto
      - name: Check Project
        run: |
          Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")'
